#!/usr/bin/python3

alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

def new_word_generator():
  num_char = len(text)
  the_message = ''
  for i in range(0, num_char):
    if direction == "encode":
      shifted_index = alphabet.index(text[i]) + shift % 26
      specified_action = "encrypted" 
    else:
      shifted_index = alphabet.index(text[i]) - shift % 26
      specified_action = "decrypted"
    shifted_char = alphabet[shifted_index]
    the_message += shifted_char
  print(f"the {specified_action} text is {the_message}")  

direction = input("Type 'encode' to encrypt, type 'decode' to decrypt:\n") 

if direction == "encode" or direction == "decode":
  text = input("Type your message:\n").lower()
  shift = int(input("Type the shift number:\n"))
  new_word_generator()
else: 
  print("Invalid Input! The options are 'encode' and 'decode'")
