#!/usr/bin/python3

alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

direction = input("Type 'encode' to encrypt, type 'decode' to decrypt:\n")
text = input("Type your message:\n").lower()
shift = int(input("Type the shift number:\n"))


def encrypt(text, shift):
  num_char = len(text)
  encrypted_message = ''
  
  for i in range(0, num_char):
    shifted_index = alphabet.index(text[i]) + shift
    shifted_index = shifted_index % 26
    shifted_char = alphabet[shifted_index]
    encrypted_message += shifted_char
  print(f"the encoded text is {encrypted_message}")


def decrypt(text, shift):
  num_char = len(text)
  decrypted_message = ''
  
  for i in range(0, num_char):
    shifted_index = alphabet.index(text[i]) - shift
    shifted_index = shifted_index % 26
    shifted_char = alphabet[shifted_index]
    decrypted_message += shifted_char
  print(f"the decoded text is {decrypted_message}")

if direction == "encode":
  encrypt(text, shift)
elif direction == "decode":
  decrypt(text, shift)
else: 
  print("Invalid Input! The options are 'encode' and 'decode'")
